### ISSUE TITLE
Incomplete LICENSE file

### ISSUE THREAD

**Issue by rrrlw** [VBlesius/RHRT#3]
[LICENSE](https://github.com/VBlesius/RHRT/blob/main/LICENSE) file (GPL-2) is missing a couple of fields:
* line 293
* line 294
* could adjust the sample (line 312 to end)

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3540).

**Comment by VBlesius** [comment]
Thank you for the feedback! The mentioned lines in the licence file serve as examples how to adapt ones program to the GPL. To our knowledge they are not meant to be adapted themselves. 

We checked the [instructions](https://www.gnu.org/licenses/gpl-howto.html) of the licence again and found no mention of the need to adapt the licence file. However, we did not include copyright and licence notices which is recommended. We corrected this oversight here: 2aeba4cf710745fecd91b4a64b451cde8907b36c.
