### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by rrrlw** [VBlesius/RHRT#4]
I don't see any explicit contributor guidelines in this repository. If I missed them, please share the link and I will correct my oversight. Otherwise, options for reasonable fixes would include (but are not limited to) including a contributions section in the repo README or including a separate CONTRIBUTING.md file (e.g. [Contributor Covenant](https://www.contributor-covenant.org/)).

The contribution guidelines should guide "third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support".

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/3540).

**Comment by VBlesius** [comment]
You are absolutely right, until now we did not mention contributions in the repo. I included a short passage inviting contributions in the README which I hope is sufficient (316a022deefd03687565a09a1a1fd85171874660). 
And thank you very much for suggesting contributor covenant, I also included it in the repo.
